version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/microServiceJEE7-1.0-SNAPSHOT.jar